name: Build GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
      - name: Install Node Dependencies
        run: npm i
      - name: Build Page
        run: npm run build
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: page-build # The branch the action should deploy to.
          folder: 'build' # The folder the action should deploy.