name: Build GitHub Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
      - name: Install Node Dependencies
        run: npm i
      - name: Build Page
        run: npm run build
      - name: Configure Git
        run: git config --global user.email "justsailor06@gmail.com"
      - name: Deploy Page
        run: npm run deploy